# Generated by Django 4.0 on 2022-05-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_image_label_labeledimage_image_labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'default_permissions': (), 'ordering': ('slug',), 'verbose_name': 'Label', 'verbose_name_plural': 'Labels'},
        ),
        migrations.AlterField(
            model_name='label',
            name='slug',
            field=models.CharField(db_index=True, help_text='The slug of the label.', max_length=1024, unique=True),
        ),
    ]
