# Generated by Django 4.0 on 2022-05-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_image_filename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'default_permissions': (), 'ordering': ('filename',), 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='uri',
            field=models.TextField(help_text='The path of the image relative to manage.py.'),
        ),
    ]
