# Generated by Django 4.0 on 2022-06-01 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labeledimage',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='labeledimage',
            name='is_active',
        ),
    ]
