# Generated by Django 4.0 on 2022-06-05 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_label_deleted_at_remove_label_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeledimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labeled_images', to='core.image'),
        ),
        migrations.AlterField(
            model_name='labeledimage',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labeled_images', to='core.label'),
        ),
    ]
